---
# tasks file for ansible-role-ohpc-setup

- name: install OpenHPC base, warewulf, and slurm server
  yum: name={{ item }} state=present
  with_items:
    - "ohpc-base"
    - "ohpc-warewulf"

- name: config warewulf interface
  lineinfile: dest=/etc/warewulf/provision.conf regexp="network device =" line="network device = {{ internal_interface }}" 

- name: enable tftp
  lineinfile: dest=/etc/xinetd.d/tftp regexp="^(\s+)disable(\s+)= yes" line="\1disable\2= no" backrefs=yes
  notify: restart xinetd

- name: exportfs opt entry on headnode
  lineinfile: line="/opt/ohpc/pub {{ internal_net }}(ro,no_subtree_check,fsid=11)" dest=/etc/exports state=present
  notify: restart nfs

- name: initialize database
  command: wwinit database

- name: cluster ssh keys
  command: wwinit ssh_keys
  args:
    chdir: /root/
    creates: /etc/warewulf/vnfs/ssh/ssh_host_key.pub

- name: Generate ww chroot images
  command: wwmkchroot centos-7 {{ item }}
  #delegate_to: localhost
  with_items: "{{ groups.ohpc_images }}"

- name: upgrade all packages in OpenHPC images
  yum:
    name: '*'
    state: latest
    installroot: "{{ item }}"
  with_items: "{{ groups.ohpc_images }}"

- name: Install OpenHPC client packages and yum to ww image chroot(s)
  yum:
    name: "{{ packages }}"
    state: present
    installroot: "{{ item }}"
  vars:
    packages:
      - ohpc-base-compute
      - yum
  with_items: "{{ groups.ohpc_images }}"

- name: Copy resolv.conf to ww image chroots
  copy: src=/etc/resolv.conf dest={{ item }}/etc/resolv.conf owner=root mode=0644
  with_items: "{{ groups.ohpc_images }}"
