---
# handlers file for ansible-role-ohpc-setup

- name: restart xinetd
  service: name=xinetd state=restarted enabled=yes

- name: exportfs reload
  listen: restart nfs
  command: exportfs -a

#- name: restart rpcbind
#  listen: restart nfs
#  service: name=rpcbind state=restarted enabled=yes

- name: restart nfs-server
  listen: restart nfs
  service: name=nfs-server state=restarted enabled=yes

# For some reason yum --installroot doesn't work here
- name: reinstall glibc-common
  command: chroot {{ item}} yum -y reinstall glibc-common
  loop: "{{ groups.ohpc_images }}"


- name: restart tftp
  systemd:
    name: "{{ tftp_service }}"
    daemon-reload: true
    state: restarted
